# Generated by Django 4.1.5 on 2023-02-07 09:25

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(8, message='Verify length'), django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^[0-9]{8}$', message='digits only !')], verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.models.is_mail_esprit]),
        ),
    ]
